include $(CLEAR_VARS)
LOCAL_MODULE := Music
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Music/Music.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)
