include $(CLEAR_VARS)
LOCAL_MODULE := Musica
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Musica/Music.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_OVERRIDES_PACKAGES := Music
include $(BUILD_PREBUILT)
